### ISSUE TITLE
mermaid not found

### ISSUE THREAD

**Issue by olafklingt** [raghur/mermaid-filter#14]
I guess this issue is more like that i didn't install something properly but i don't know what i have to install. after this command:
pandoc -t html -F mermaid-filter -o output.html test.md

The error message is the following:

External tool not found: mermaid
pandoc: Error running filter mermaid-filter

i tried to install mermaid from npm:

npm install -g mermaid 

but it does not change my situation.

I am on os x 10.10.4 
many thanks
olaf

**Comment by raghur** [comment]
Are you on Windows? If so, you have to specify the extension and/or also
modify the cmd file. See this portion from the README:

*WINDOWS* - you need mermaid-filter.cmd in the line above

*Windows 8.1* - On windows 8.1, mermaid-filter.cmd fails - apparently due
to change in how the CMD.exe works for subprocesses? - see this issue thread
<https://github.com/jgm/pandoc/issues/3458>. You have to edit the globally
installed mermaid-filter.cmd located in
c:\users\<username>\AppData\Roaming\npm to use ~dp$PATH:0. Unfortunately,
you will need to do this each time you install/update mermaid-filter since
it overwrites the cmd file.

**Comment by larsw** [comment]
Related; which mermaid version is this package supposed to work with? The original mermaid CLI is deprecated in favor of the mermaid.cli package, which installs mmdc/mmdc.cmd, but hasn't the same arguments (as far as I know).

**Comment by olafklingt** [comment]
sorry for the late answer

i am on os x 

i tried to exchange the cmd variable within the index.js to

`var cmd = externalTool("/usr/local/bin/mmdc") + " -v -e " + phantomjs.path;`

but it does not work because the arguments are different but i don't know the meaning of the old arguments so it is difficult to translate further. 

for now i use the pandoc-mermaid filter, but that works only works for html

**Comment by raghur** [comment]
I see... tbh, I haven't been tracking mermaid that closely - so didn't know
that cli args/entrypoint had changed. Will take a look and fix it up.

Thanks for the bug report.

**Comment by raghur** [comment]
I've just pushed a commit that should address this. Can you install again and see if it works for you?

**Comment by larsw** [comment]
Thanks! That worked out. Just FYI; I submitted a PR for PDF support in mermaid.cli that was merged recently. I'm also currently working on SVG->EMF conversion via Inkscape so that it will be possible to import the diagrams as vector graphic in docx (Word < 2016). Word 2016 supports SVG as far as I know, but our corp hasn't upgraded yet.

**Comment by olafklingt** [comment]
perfect thanks!
