### ISSUE TITLE
Support RestructuredText as well as Markdown

### ISSUE THREAD

**Issue by gappleto97** [raghur/mermaid-filter#24]
It would be nice if I could use this when I am writing papers. Most of the time I use RestructuredText, since that is also what I have to use at work for documentation, and since it allows a lot prettier latex usage.

I'm willing to contribute a PR, but haven't made a pandoc filter before, so don't know what that entails.

**Comment by raghur** [comment]
@gappleto97 you get that for free :) since pandoc filters operate on pandoc's intermediate json representation

doc.rst:

```rst
This is is a reStructured Text document.

Let's see if mermaid filter works with a rest code block

.. code:: 
 :class: mermaid

    sequenceDiagram
        Alice->>John: Hello John, how are you?
        John-->>Alice: Great!

```

can be rendered with 
`pandoc -f rst -t html -F mermaid-filter -o out.html`

I don't use RST much - but I think you should be able to pass in options in a way analogous to markdown
