### ISSUE TITLE
Windows: Could not find executable pandoc-mermaid

### ISSUE THREAD

**Issue by tatoosh** [raghur/mermaid-filter#34]
I can't get mermaid filter to work on Windows 10.

pandoc --version: 2.2.1
Installed with npm: `npm install --global mermaid-filter`

What does that mean:
> WINDOWS - you need mermaid-filter.cmd in the line above

By running AppData\Roaming\npm\mermaid-filter.cmd nothing happens.

Thx

**Comment by raghur** [comment]
It means `pandoc -t html -F mermaid-filter -o something.html something.md` the -F param should spell it out as `mermaid-filter.cmd`

Are you running that directly? It'll just sit there since it's a filter waiting for input. You can only use it as a pandoc filter.
Also note the para in the readme afterwards - based on your windows, you might have to update the .cmd file by hand...

**Comment by raghur** [comment]
try this

pandoc -t html -F mermaid-filter.cmd -o 1.html test.md

**Comment by tatoosh** [comment]
with the suffix `.cmd` something is working ;)
Now i get this error:

> Error running filter mermaid-filter.cmd:
> Error in $: Failed reading: not a valid json value

Maybe i have to fix the `mermaid-filter.cmd` - but how? thx a lot!

**Comment by raghur** [comment]
Reopen if you still have a question
